on: [issues]

jobs:
  create_comment:
    runs-on: ubuntu-latest
    steps:
      # To use this repository's private action,
      # you must check out the repository
      - name: Checkout
        uses: actions/checkout@v2
        with:
          repository: manuelaesitx/issuechecker
          ref: main
          token: ${{ secrets.GITHUB_TOKEN }}
          path: .github/actions
      - name: Check issue content step
        uses: ./.github/actions/issuechecker/code/roadmap-issue-checker
        id: check_issue
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
